"""new def & fields

Revision ID: 84123f6c0e6f
Revises: aafb8679805a
Create Date: 2019-06-25 20:47:03.116020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84123f6c0e6f'
down_revision = 'aafb8679805a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('t_desc', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 't_desc')
    # ### end Alembic commands ###
