"""added deadline

Revision ID: a4dcfbf99e99
Revises: 84123f6c0e6f
Create Date: 2019-07-15 18:26:59.981639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dcfbf99e99'
down_revision = '84123f6c0e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ddate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_ddate'), 'task', ['ddate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_ddate'), table_name='task')
    op.drop_column('task', 'ddate')
    # ### end Alembic commands ###
